apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/argo
    repoURL: https://github.com/christianbotia35/stack_andres
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true